package com.example.dawanow.entity;

public enum ChatIntent {
    GREETING,
    MEDICINE_REQUEST,
    SYMPTOM_ADVICE,
    DOCTOR_SPECIALIZATION,
    EMERGENCY,
    MEDICINE_USAGE,
    ADD_TO_CART,
    CREATE_REQUEST,
    SET_REMINDER,
    DELETE_REMINDER,
    LIST_REMINDERS,
    OTHER
}
